version: "2"

volumes:
  homebridge:

services:
  mdns-publisher:
    build: ./mdns-publisher
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    labels:
      io.balena.features.dbus: "1"
  homebridge:
    build: ./homebridge
    restart: always
    network_mode: host
    volumes:
      - homebridge:/homebridge
