FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:bookworm
ENV UDEV=on
RUN apt-get update && \
    apt-get install ffmpeg moreutils

COPY ./start.sh /usr/bin/start.sh
COPY ./rclone-v1.68.2-linux-arm64/rclone /usr/bin/rclone
CMD [ "/usr/bin/start.sh" ]